name: ShulkerBoxDrop
version: '${project.version}'
main: bianloveyue.shulkerboxdrop.ShulkerBoxDrop
api-version: '1.16'
author: bianloveyue
website: https://klpbbs.com/home.php?mod=space&uid=1637116&do=thread&view=me&from=space
commands:
  shulkerboxdrop:
    description: A command to toggle the shulker box drop plugin
    usage: /shulkerboxdrop
    permission: shulkerboxdrop.shulkerboxdrop
permissions:
  shulkerboxdrop.shulkerboxdrop:
    description: Allows using the shulkerboxdrop command
    default: op

